[package]
name = "amir_arch_x86_64"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
amir_hal = { path = "../../hal" }
amir_mm = { path = "../../mm" }
free-list = "0.3.3"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
log = "0.4.32"
memory_addr = "0.4.1"
page_table_multiarch = "0.6.1"
spin = "0.12.0"
x86_64 = "0.15.4"
