[package]
name = "amir_arch"
version.workspace = true
edition.workspace = true
license.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
amir_arch_x86_64 = { path = "x86_64" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
amir_arch_riscv64 = { path = "riscv64" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
amir_arch_aarch64 = { path = "aarch64" }

[target.'cfg(target_arch = "loongarch64")'.dependencies]
amir_arch_loongarch64 = { path = "loongarch64" }
